---
- hosts: all
  sudo: true
  vars:
    username: ansible
    usergroups: adm

  tasks:
    # http://docs.ansible.com/ansible/user_module.html
    - name: Create `ansible` user
      user:
        name: "{{ username }}"
        groups: "{{ usergroups }}"
        createhome: no

    # http://docs.ansible.com/ansible/file_module.html
    - name: Create `.ssh` directory
      file:
        path: "/home/{{ username }}/.ssh/"
        state: directory

    # http://docs.ansible.com/ansible/authorized_key_module.html
    - name: Add SSH key as authorized key
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
